name: Python CI with Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-behave

    - name: Run tests with Allure
      run: |
        source venv/bin/activate
        behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results

    - name: Upload Allure report artifacts
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: reports/allure-results
