name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Instalar dependências
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar testes com Behave
      run: |
        source venv/bin/activate
        mkdir -p reports
        behave --format pretty --format html --out reports/report.html

    - name: Upload do relatório (opcional)
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/report.html
